WebApplication2/Controllers/FacearController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication2.Controllers
{
    public class FacearController : Controller
    {
        // GET: Facear
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Sobre()
        {
            return View();
        }
        public ActionResult Profesores()
        {
            return View();
        }
        public ActionResult Cursos()
        {
            return View();
        }
    }
}

WebApplication2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Aulas MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <strong style="color:green">UNIFACEAR</strong>
        <div>
            <table width="100%">
                <tr>
                    <td> <a href="Facear/Index"> PRINCIPAL</a> </td>
                    <td>  @Html.ActionLink("Veja Sobre", "Sobre", "Facear")</td>
                    <td>  @Html.ActionLink("Professores", "Profesores", "Facear")</td>
                    <td> @Html.ActionLink("Cursos", "Cursos", "Facear")</td>

                </tr>
            </table>

        </div>

        @*@RenderPage("~/Views/Shared/_Topo.cshtml")*@
        @RenderBody()

        @if (IsSectionDefined("rodape"))
        {
               @RenderSection("rodape")
        }
        else
        {
            @Html.Partial("_Rodape");

        }
        @RenderPage("~/Views/Shared/_Menu.cshtml")

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication2/Views/Shared/_Menu.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html  >
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body >
    <div >
        
    
    </div>
</body>
</html>

WebApplication2/Views/Shared/_Rodape.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h3>AQUI FICA O RODAPE GERALL</h3>
    </div>
</body>
</html>

WebApplication2/Views/Shared/_Topo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h1>AQUI FICA O TOPO DO NOSSO SITE</h1>
    </div>
</body>
</html>