Prova_Junior_2/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace Prova_Junior_2.Models
{
    public class Produto
    {
        public int Id_Produtos { get; set; }
        public string Nome { get; set; }
        [Required(ErrorMessage = "Preço Campo é obrigatório")]
        public string Preco { get; set; }
        [Required(ErrorMessage = "Descricão Campo é obrigatório")]
        public string Descricao { get; set; }
        public string Marca { get; set; }
        [Required(ErrorMessage = "Modelo Campo é obrigatório")]
        public string Modelo { get; set; }

        public void Cadastrar()

        {
            SqlConnection conec = new SqlConnection("Data Source=.;Initial Catalog=Mvc_Junior;Integrated Security=True");
            SqlCommand comando = new SqlCommand("INSERT INTO Produto VALUES('" + this.Nome + "','" + this.Preco + "','" + this.Descricao + "','" + this.Marca + "','" + this.Modelo + "')", conec);
            conec.Open();
            comando.ExecuteNonQuery();//salva e não retorna nennhum valor.
            conec.Close();
        }
        public static List<Produto> Lista_Produto()
        {
            List<Produto> Lista_produtos = new List<Produto>();
            SqlConnection conec = new SqlConnection("Data Source=.;Initial Catalog=Mvc_Junior;Integrated Security=True");
            SqlCommand comando = new SqlCommand("SELECT * FROM Produto", conec);
            conec.Open();

            Produto produto = new Produto();
            SqlDataReader dr = comando.ExecuteReader();
            while (dr.Read())
            {
                Lista_produtos.Add(new Produto()
                {
                    Id_Produtos = Convert.ToInt32(dr["Id_Produtos"]),
                    Nome = dr["Nome"].ToString(),
                    Preco = dr["Preco"].ToString(),
                    Descricao = dr["Descricao"].ToString(),
                    Marca = dr["Marca"].ToString(),
                    Modelo = dr["Modelo"].ToString(),
                });
            }

            dr.Close();
            return Lista_produtos;
        }
        public List<Produto> Lista_ProdutoID(int id)
        {
            List<Produto> Lista_Produtos = new List<Produto>();
            SqlConnection conec = new SqlConnection("Data Source=.;Initial Catalog=Mvc_Junior;Integrated Security=True");
            SqlCommand comando = new SqlCommand("SELECT * FROM  Produto  where Id_Produtos =" + id + ";", conec);
            conec.Open();

            Produto produto = new Produto();
            SqlDataReader dr = comando.ExecuteReader();
            while (dr.Read())
            {
                Lista_Produtos.Add(new Produto()
                {
                    Id_Produtos = Convert.ToInt32(dr["Id_Produtos"]),
                    Nome = dr["Nome"].ToString(),
                    Preco = dr["Preco"].ToString(),
                    Descricao = dr["Descricao"].ToString(),
                    Marca = dr["Marca"].ToString(),
                    Modelo = dr["Modelo"].ToString(),
                });
            }

            dr.Close();
            return Lista_Produtos;
        }
        public void Alterar_Produto(Produto produto)
        {
            SqlConnection connec = new SqlConnection("Data Source=.;Initial Catalog=Mvc_Junior;Integrated Security=True");
            SqlCommand comando = new SqlCommand("UPDATE Produto SET Nome='" + produto.Nome + "', Preco='" + produto.Preco + "', Descricao='" + produto.Descricao + "', Marca='" + produto.Marca + "', Modelo='" + produto.Modelo + "' WHERE Id_Produtos = " + produto.Id_Produtos + "; ", connec);
            connec.Open();
            comando.ExecuteNonQuery();
            connec.Close();
        }
        public void Excluir(Produto produto)
        {
            SqlConnection conec = new SqlConnection("Data Source=.;Initial Catalog=Mvc_Junior;Integrated Security=True");
            SqlCommand comando = new SqlCommand("DELETE from Produto  where Id_Produtos =" + produto.Id_Produtos + ";", conec);

            conec.Open();
            comando.ExecuteNonQuery();//salva e não retorna nennhum valor.
            conec.Close();
        }
        public static  List<Produto> Lista_Produto_MODELO(string modelo)
        {
            List<Produto> Lista_Produtos = new List<Produto>();
            SqlConnection conec = new SqlConnection("Data Source=.;Initial Catalog=Mvc_Junior;Integrated Security=True");
            SqlCommand comando = new SqlCommand("SELECT * FROM  Produto  where Modelo ='" + modelo + "';", conec);
            conec.Open();

            Produto produto = new Produto();
            SqlDataReader dr = comando.ExecuteReader();
            while (dr.Read())
            {
                Lista_Produtos.Add(new Produto()
                {
                    Id_Produtos = Convert.ToInt32(dr["Id_Produtos"]),
                    Nome = dr["Nome"].ToString(),
                    Preco = dr["Preco"].ToString(),
                    Descricao = dr["Descricao"].ToString(),
                    Marca = dr["Marca"].ToString(),
                    Modelo = dr["Modelo"].ToString(),
                });
            }

            dr.Close();
            return Lista_Produtos;
        }


    }
}

Prova_Junior_2/Controllers/Menu_Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prova_Junior_2.Controllers
{
    public class Menu_Controller : Controller
    {
        // GET: Menu_
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Menu_()
        {
            return View();
        }
        public ActionResult Menu_USUARIO()
        {
            return View();
        }
        

        // return Redirect("/Menu/EsporteUsuario"); Retona para view de fora da pagina
    }
}

Prova_Junior_2/Controllers/ProdutoController.cs
using Prova_Junior_2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Prova_Junior_2.Controllers
{
    public class ProdutoController : Controller
    {
        List<Produto> produto_lista = Produto.Lista_Produto();

        List<Produto> produto_lista_Modelo_Celular = Produto.Lista_Produto_MODELO("Celular");
        List<Produto> produto_lista_Modelo_Tablet = Produto.Lista_Produto_MODELO("Tablet");
        List<Produto> produto_lista_Modelo_Not = Produto.Lista_Produto_MODELO("Not");
        List<Produto> produto_lista_Modelo_Carregadores = Produto.Lista_Produto_MODELO("Carregador");

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Celular()
        {
            return View(produto_lista_Modelo_Celular);
        }
        public ActionResult Not()
        {
            return View(produto_lista_Modelo_Not);
        }
        public ActionResult Tablet()
        {
            return View(produto_lista_Modelo_Tablet);
        }
        public ActionResult Carregadores()
        {
            return View(produto_lista_Modelo_Carregadores);
        }

        public ActionResult Alterar(int id)
        {

            Produto produto = new Produto();
            return View(produto.Lista_ProdutoID(id)[0]);

        }
        public ActionResult Dados_Produtos(int id)
        {

            Produto produto = new Produto();
            return View(produto.Lista_ProdutoID(id)[0]);
        }
        
        public ActionResult Excluir(int id)
        {
            Produto produto = new Produto();
            return View(produto.Lista_ProdutoID(id)[0]);
        }
        public ActionResult Listar()
        {
            return View(produto_lista);
        }
        [HttpPost]
        public ActionResult Cadastrar(Produto produto)
        {
            if (!ModelState.IsValid)
            {
                return View(produto);
            }
            else
            {
                produto.Cadastrar();
                ModelState.Clear();
                return Redirect("/Menu_/Menu_");
            }
        }
        [HttpPost]
        public ActionResult Alterar(Produto produto)
        {
            produto.Alterar_Produto(produto);
            //return View();
            return Redirect("/Produto/Listar");
        }

        [HttpPost]
        public ActionResult Excluir(int id, FormCollection form)
        {
            Produto produto = new Produto();
            produto = produto.Lista_ProdutoID(id)[0];
            produto.Excluir(produto);
            return Redirect("/Produto/Listar");
        }
    }
}

Prova_Junior_2/Views/Produto/Alterar.cshtml
@model Prova_Junior_2.Models.Produto

@{
    ViewBag.Title = "Alterar";
}

<h2>Alterar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Produto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_Produtos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_Produtos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_Produtos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar a lista", "Listar")
</div>
@section rodape{
   
}

Prova_Junior_2/Views/Produto/Cadastrar.cshtml
@model Prova_Junior_2.Models.Produto

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <form method="post">
        <div class="form-horizontal">
            <h4>Produto</h4>
            <hr />


            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Modelo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Modelo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Modelo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </form>
}


@section Scripts{

    @Scripts.Render("~/bundles/jqueryval")
}

<div>
    @Html.ActionLink("Menu", "Menu_", "Menu_")
</div>
@section rodape{

}

Prova_Junior_2/Views/Produto/Carregadores.cshtml
@model IEnumerable<Prova_Junior_2.Models.Produto>

@{
    ViewBag.Title = "Carregadores";
}

<h2>Carregadores</h2>

<p>
    @Html.ActionLink("Voltar", "Menu_USUARIO", "Menu_")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_Produtos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Produtos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>

            @Html.ActionLink("Detalhes", "Dados_Produtos", new { id = item.Id_Produtos }) |

        </td>
    </tr>
}

</table>

Prova_Junior_2/Views/Produto/Celular.cshtml
@model IEnumerable<Prova_Junior_2.Models.Produto>

@{
    ViewBag.Title = "Celular";
}

<h2>Celular</h2>

<p>
    @Html.ActionLink("Voltar", "Menu_USUARIO", "Menu_")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_Produtos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Produtos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>
            @Html.ActionLink("Detalhes", "Dados_Produtos", new { id = item.Id_Produtos }) |
        </td>
    </tr>
}

</table>

Prova_Junior_2/Views/Produto/Dados_Produtos.cshtml
@model Prova_Junior_2.Models.Produto

@{
    ViewBag.Title = "Dados_Produtos";
}

<h2>Dados_Produtos</h2>

<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">


        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar menu", "Menu_USUARIO", "Menu_") <br />
</p>
@section rodape{

    <style>
        .footer {
            background-color: red;
            width: 100%;
            height: 50px;
            float: right;
            text-align: center;
        }
    </style>
    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title> RODAPE GERAL</title>
    </head>
    <body>
        <div class="footer">
            <text>RODAPE DADOS DE PRODUTOS AQUI É DIFERENTE</text>
        </div>
    </body>
}

Prova_Junior_2/Views/Produto/Excluir.cshtml
@model Prova_Junior_2.Models.Produto

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Deseja excluir este PRODUTO?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id_Produtos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_Produtos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Modelo)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("VOLTAR A LISTA", "Listar")
        </div>
    }
</div>
@section rodape{

}

Prova_Junior_2/Views/Produto/Listar.cshtml
@model IEnumerable<Prova_Junior_2.Models.Produto>

@{
                /**/

                ViewBag.Title = "Listar";
}

<h2>Listar</h2>

<p>
    @Html.ActionLink("Novo Produto", "Cadastrar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_Produtos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Id_Produtos)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nome)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Preco)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Descricao)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Marca)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Modelo)
    </td>
    <td>
        @Html.ActionLink("Editar", "Alterar", new { id = item.Id_Produtos }) |
        @Html.ActionLink("Excluir", "Excluir", new { id = item.Id_Produtos })
    </td>
</tr>
}

</table>
@section rodape{

}

Prova_Junior_2/Views/Produto/Not.cshtml
@model IEnumerable<Prova_Junior_2.Models.Produto>

@{
    ViewBag.Title = "Not";
}

<h2>Not</h2>

<p>
    @Html.ActionLink("Voltar", "Menu_USUARIO", "Menu_")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_Produtos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Produtos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>
            @Html.ActionLink("Detalhes", "Dados_Produtos", new { id = item.Id_Produtos }) |
        </td>
    </tr>
}

</table>

Prova_Junior_2/Views/Produto/Tablet.cshtml
@model IEnumerable<Prova_Junior_2.Models.Produto>

@{
    ViewBag.Title = "Tablet";
}

<h2>Tablet</h2>

<p>
    @Html.ActionLink("Voltar", "Menu_USUARIO", "Menu_")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_Produtos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Modelo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id_Produtos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Modelo)
        </td>
        <td>

            @Html.ActionLink("Detalhes", "Dados_Produtos", new {  id=item.Id_Produtos }) |

        </td>
    </tr>
}

</table>