WebApplication2/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class AlunoController : Controller
    {
        // GET: Aluno

        public static List<Aluno> listaAlunos = new List<Aluno>();
        string listadealunos;
        static int resultado = 0;
    
        public ActionResult Index()
        {


            return View();
        }

        public ActionResult Create()
        {
            return View();   
        }
        [HttpPost]
        public ActionResult Create(int txt_id, string txt_nome, int txt_idade)
        {
            if (txt_idade < 18)
            {
                ViewBag._mensagem = "A idade não pode ser menor que 18. Verefique a idade";
                ViewBag._id = txt_id;
                ViewBag._idade = txt_idade;
                ViewBag._nome = txt_nome;
            }
            else
            {
                Aluno aluno = new Aluno();
                aluno.Id_pessoa = txt_id;
                aluno.Idade = txt_idade;
                aluno.Nome = txt_nome;

                listaAlunos.Add(aluno);

                for (int i = 0; i < listaAlunos.Count; i++)
                {
                    listadealunos = listadealunos + ", " + listaAlunos[i].Nome;
                }

                ViewBag._lista = listadealunos;

                //parametro por viewBAG
                ViewBag._id = "";
                ViewBag._idade = "";
                ViewBag._nome = "";
                ViewBag._mensagem = "";

                ////parametro por viewDATA
                //ViewData["Id_Pessoa"] = aluno.Id_pessoa;
                //ViewData["Nome"] = aluno.Nome;
                //ViewData["Idade"] = aluno.Idade;
            }
            return View();
        }

        public ActionResult Soma()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Soma(int txt_valor)
        {
            resultado = (txt_valor + (resultado));
            ViewBag._valor = txt_valor;
            ViewData["resultado"] = resultado;

            if (resultado % 2 == 0)
            {
                ViewBag._tipo = "NUMERO PAR";
                ViewBag._cor = "color:forestgreen";

               
            }
            else
            {
                ViewBag._tipo = "NUMERO IMPAR";
                ViewBag._cor = "color:red";
 
            }
            return View();
        }
        public ActionResult New_Aluno()
        {
            return View();

        }
        [HttpPost]
        public ActionResult New_Aluno(FormCollection form)
        {

            Pessoa p1 = new Pessoa();
            p1.Nome = form["txt_nome"];
            p1.Idade = Convert.ToInt32(form["txt_idade"]);
            return View();

        }
        public ActionResult Novo_Aluno()
        {
            return View();
        }
        [HttpPost]
        // pra passar somente um objeto ou mais de um usar o colection.
        public ActionResult Novo_Aluno(Aluno aluno, FormCollection form)
        {
            bool validadados = true;

            if (string.IsNullOrEmpty(aluno.Nome))
            {
                ModelState.AddModelError("", "Campo nome obrigatorio");
                validadados = false;
            }

            if (!aluno.Idade.HasValue)
            {
                ModelState.AddModelError("", "Campo idade obrigatorio");
                validadados = false;
            }

            if (string.IsNullOrEmpty(aluno.Sexo))
            {
                ModelState.AddModelError("Sexo", "*Campo Sexo é obrigatorio");
                validadados = false;
            }
            else if (aluno.Sexo != ("F") && (aluno.Sexo != ("M")))
            {
                ModelState.AddModelError("", "*Campo sexo tem que ser M ou F");
                validadados = false;
            }

            if (!aluno.Peso.HasValue)
            {
                ModelState.AddModelError("Peso", "*Campo Peso é obrigatorio");
                validadados = false;
            }
            else if (aluno.Peso>300)
            {
                ModelState.AddModelError("", "*Campo Pesodeve ser menor que 300");
                validadados = false;
            }
            else if (aluno.Peso < 0) {
                ModelState.AddModelError("", "*Campo Peso de ser maior que 0");

                validadados = false;
            }
            try
            {
                if (validadados==true)
                {
                    aluno.Cadastrar();
                    ViewBag.Status = "Dados gravados com Êxito";
                    ModelState.Clear();
                    return View();
                }               
            }
            catch 
            {
            }
            return View();
        }
    }
}

WebApplication2/Controllers/CadastrarPessoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class CadastrarPessoaController : Controller
    {
        // GET: CadastrarPessoa
        List<Pessoa> pessoas = Pessoa.Lista_Pessoas();
    
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult Menu_()
        {
            return View();
        }
        public ActionResult Alterar_()
        {
            return View();
        }
        public ActionResult Cadastrar_()
        {
            return View();
        }
        public ActionResult Listar_()
        {
            return View(pessoas);
        }
        public ActionResult Login_()
        {
            return View();
        }

        public ActionResult ListaTodos()
        {
            return View(pessoas);
        }
      
        public ActionResult EditarTodos(int id)
        {
            Pessoa pessoa = new Pessoa();
            return View(pessoa.Lista_Pessoas_ID(id)[0]);
        }

        [HttpPost]
        public ActionResult EditarTodos(Aluno aluno)
        {
            aluno.Alterar(aluno);
            //return View();
            return RedirectToAction("ListaTodos");
        }
        [HttpPost]
        public ActionResult Excluir_(int id, FormCollection form)
        {
            Pessoa pessoa = new Pessoa();
            pessoa=pessoa.Lista_Pessoas_ID(id)[0];
            pessoa.Excluir(pessoa);
            return RedirectToAction("ListaTodos");
        }
        public ActionResult Excluir_(int id )
        {
            Pessoa pessoa = new Pessoa();
            return View(pessoa.Lista_Pessoas_ID(id)[0]);
        }
        [HttpPost]
        public ActionResult Cadastrar(Aluno aluno, FormCollection form)
        {
                bool validadados = true;

                if (string.IsNullOrEmpty(aluno.Nome))
                {
                    ModelState.AddModelError("", "Campo nome obrigatorio");
                    validadados = false;
                }

                if (!aluno.Idade.HasValue)
                {
                    ModelState.AddModelError("", "Campo idade obrigatorio");
                    validadados = false;
                }

                if (string.IsNullOrEmpty(aluno.Sexo))
                {
                    ModelState.AddModelError("Sexo", "*Campo Sexo é obrigatorio");
                    validadados = false;
                }
                else if (aluno.Sexo != ("F") && (aluno.Sexo != ("M")))
                {
                    ModelState.AddModelError("", "*Campo sexo tem que ser M ou F");
                    validadados = false;
                }

                if (!aluno.Peso.HasValue)
                {
                    ModelState.AddModelError("Peso", "*Campo Peso é obrigatorio");
                    validadados = false;
                }
                else if (aluno.Peso > 300)
                {
                    ModelState.AddModelError("", "*Campo Pesodeve ser menor que 300");
                    validadados = false;
                }
                else if (aluno.Peso < 0)
                {
                    ModelState.AddModelError("", "*Campo Peso de ser maior que 0");

                    validadados = false;
                }
                try
                {
                    if (validadados == true)
                    {
                        aluno.Cadastrar();
                        ViewBag.Status = "Dados gravados com Êxito";
                        ModelState.Clear();
                    return RedirectToAction("Login_");
                    
                    }
                }
                catch
                {
                }
                return View();
        }

        [HttpPost]
        public ActionResult Login_(string Nome, String Cpf)
        {
            return RedirectToAction("Menu_");
        }         
    }
}

WebApplication2/Views/CadastrarPessoa/Cadastrar_.cshtml
@model WebApplication2.Models.Aluno
@{
    ViewBag.Title = "Novo_Aluno";
}

<style>
    .validation-summary-errors {
        color: red;
    }

    .minhaclasse {
        color: blue;
    }

    .minhaclasse2 {
        color: red;
    }
</style>
<h2>Cadastrar Aluno</h2>
@*<form method="post">*@
@using (Html.BeginForm("Novo_Aluno", "Aluno", FormMethod.Post))
{
    @Html.ValidationSummary(true)
    @*NOME:*@
    @*<input type="text" id="Nome" name="Nome" />*@
    @*helpers*@
    @Html.LabelFor(x => x.Nome, new { @class = "minhaclasse" })
    @Html.TextBoxFor(x => x.Nome)
    <br />
    @Html.LabelFor(x => x.Idade)
    @Html.TextBoxFor(x => x.Idade)
    <br />
    @Html.LabelFor(x => x.Sexo)
    @Html.TextBoxFor(x => x.Sexo)
    @Html.ValidationMessageFor(x => x.Sexo)

    <br />

    @Html.LabelFor(x => x.Peso)
    @Html.TextBoxFor(x => x.Peso)
    @Html.ValidationMessageFor(x => x.Peso)

    @*IDADE:
        <input type="text" id="Idade" name="Idade" />
        Sexo:

        <input type="text" id="Sexo" name="Sexo" />
        <br />*@
    <br />
    <input class="btn-success" type="submit" value="SALVAR" />
    <p>@ViewBag.Status</p>
    @*</form>*@
}

WebApplication2/Views/CadastrarPessoa/EditarTodos.cshtml
@model WebApplication2.Models.Pessoa

@{
    ViewBag.Title = "EditarTodos";
}

<h2>EditarTodos</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Aluno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id_pessoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id_pessoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id_pessoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Idade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Idade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sexo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.ActionLink("Volttar a lista", "ListaTodos", "CadastrarPessoa")<br />
    </div>

WebApplication2/Views/CadastrarPessoa/Excluir_.cshtml
@model WebApplication2.Models.Pessoa

@{
    ViewBag.Title = "Excluir_";
}

<h2>Excluir_</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pessoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id_pessoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id_pessoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Idade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Idade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Peso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Peso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |

        @Html.ActionLink("LISTAR", "ListaTodos", "CadastrarPessoa")<br />
    </div>
    }
</div>

WebApplication2/Views/CadastrarPessoa/ListaTodos.cshtml
@model IEnumerable<WebApplication2.Models.Pessoa>
@{
    ViewBag.Title = "ListaTodos";
}
<h2>ListaTodos</h2>

<p>
    @Html.ActionLink("Cadastrar Novo", "Cadastrar_")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id_pessoa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Idade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Peso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id_pessoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Idade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Peso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.ActionLink("Alterar", "EditarTodos", new { id = item.Id_pessoa }) |

                @Html.ActionLink("Excluir", "Excluir_", new { id = item.Id_pessoa })
            </td>

        </tr>

    }

</table>

WebApplication2/Views/CadastrarPessoa/Login_.cshtml
@{
    ViewBag.Title = "Login_";
}

<h2>Login_</h2>


<form method="post">
    Nome:
    <input type="text" id="Nome" name="Nome" />
    Cpf:
    <input type="text" id="Cpf" name="Cpf" />
    <br />
    <br />
    <input class="btn-success" type="submit" value="Entrar" />
</form>
@Html.ActionLink("CADASTRAR", "Menu_", "CadastrarPessoa") <br />

WebApplication2/Views/CadastrarPessoa/Menu_.cshtml
@{
    ViewBag.Title = "Menu_";
}

<h2>Menu_</h2>



@Html.ActionLink("CADASTRAR", "Cadastrar_", "CadastrarPessoa") <br />
@Html.ActionLink("LISTAR", "ListaTodos", "CadastrarPessoa")<br />
@Html.ActionLink("ALTERAR", "EditarTodos", "CadastrarPessoa")<br />
@Html.ActionLink("ALTERAR", "Login_", "CadastrarPessoa")<br />